# Expanded NSE Universe - NIFTY 500 + High Quality Smallcaps
# ~300+ stocks covering large, mid, and liquid smallcaps
# Filtered for liquidity and data availability

NIFTY500_TICKERS = [
    # NIFTY 50 Large Caps
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS",
    "SBIN.NS", "AXISBANK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "HCLTECH.NS", "WIPRO.NS",
    "TECHM.NS", "LT.NS", "ASIANPAINT.NS", "HINDUNILVR.NS", "ITC.NS", "TITAN.NS",
    "MARUTI.NS", "M&M.NS", "EICHERMOT.NS", "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS",
    "APOLLOHOSP.NS", "DIVISLAB.NS", "ADANIENT.NS", "ADANIPORTS.NS", "POWERGRID.NS",
    "NTPC.NS", "TATAPOWER.NS", "ONGC.NS", "COALINDIA.NS", "BHARTIARTL.NS", "HINDALCO.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "GRASIM.NS", "UPL.NS", "SBILIFE.NS", "HDFCLIFE.NS",
    "ICICIPRULI.NS", "DLF.NS", "PIDILITIND.NS", "TRENT.NS", "ULTRACEMCO.NS", "NESTLEIND.NS",
    "BRITANNIA.NS", "INDUSINDBK.NS", "BAJAJ-AUTO.NS", "HEROMOTOCO.NS",
    
    # NIFTY Next 50 & Midcap Leaders
    "DMART.NS", "NYKAA.NS", "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS",
    "IDFCFIRSTB.NS", "BANDHANBNK.NS", "FEDERALBNK.NS", "AUBANK.NS", "CHOLAFIN.NS",
    "LTF.NS", "MUTHOOTFIN.NS", "ABCAPITAL.NS", "LICI.NS", "BAJAJHLDNG.NS",
    "GODREJCP.NS", "MARICO.NS", "COLPAL.NS", "DABUR.NS", "HAVELLS.NS", "PAGEIND.NS",
    "VOLTAS.NS", "SIEMENS.NS", "ABB.NS", "ASHOKLEY.NS", "ESCORTS.NS", "BOSCHLTD.NS",
    "CUMMINSIND.NS", "MOTHERSON.NS", "BHEL.NS", "IRCTC.NS", "ADANIGREEN.NS", "ADANIPOWER.NS",
    "TATACHEM.NS", "ALKEM.NS", "LUPIN.NS", "TORNTPHARM.NS", "GLENMARK.NS", "MPHASIS.NS",
    "PERSISTENT.NS", "LTIM.NS", "COFORGE.NS", "INDIAMART.NS", "POLYCAB.NS", "KEI.NS",
    "BERGEPAINT.NS", "SBICARD.NS", "AMBUJACEM.NS", "SHREECEM.NS", "GAIL.NS", "IOC.NS",
    "BPCL.NS", "TVSMOTOR.NS", "BALKRISIND.NS", "MRF.NS", "APOLLOTYRE.NS", "BATAINDIA.NS",
    
    # Pharma & Healthcare
    "LAURUSLABS.NS", "BIOCON.NS", "AUROPHARMA.NS", "GRANULES.NS", "IPCALAB.NS",
    "PFIZER.NS", "GLAXO.NS", "SANOFI.NS", "ZYDUSLIFE.NS", "ASTRAZEN.NS",
    "METROPOLIS.NS", "THYROCARE.NS", "LALPATHLAB.NS", "FORTIS.NS", "MAXHEALTH.NS",
    "NARAYANA.NS", "SYNGENE.NS",
    
    # Cement & Construction
    "JKCEMENT.NS", "RAMCOCEM.NS", "DALBHARAT.NS", "INDIACEM.NS", "HEIDELBERG.NS",
    "JKLAKSHMI.NS", "ORIENTCEM.NS", "STARCEMENT.NS", "PRISMCEM.NS",
    
    # Metals & Mining
    "VEDL.NS", "NATIONALUM.NS", "JINDALSTEL.NS", "SAIL.NS", "NMDC.NS", "HINDZINC.NS",
    "RATNAMANI.NS", "WELCORP.NS", "WELSPUNIND.NS", "APLAPOLLO.NS", "SANDUMA.NS",
    
    # IT & Tech
    "TATAELXSI.NS", "HAPPSTMNDS.NS", "TANLA.NS", "ROUTE.NS", "TATACOMM.NS",
    "KPITTECH.NS", "CYIENT.NS", "ECLERX.NS", "INTELLECT.NS", "OFSS.NS", "SONATSOFTW.NS",
    "MASTEK.NS", "ZENSARTECH.NS", "DATAPATTNS.NS",
    
    # Financial Services
    "LICHSGFIN.NS", "RECLTD.NS", "PFC.NS", "IRFC.NS", "RVNL.NS", "HUDCO.NS",
    "NBCC.NS", "REPCOHOME.NS", "IIFL.NS", "MOTILALOFS.NS",
    "ANGELONE.NS", "CDSL.NS", "MAHABANK.NS", "INDIANB.NS",
    "RBLBANK.NS", "YESBANK.NS", "CENTRALBK.NS", "IOB.NS", "SOUTHBANK.NS",
    
    # Chemicals & Fertilizers
    "DEEPAKNTR.NS", "BALRAMCHIN.NS", "CHAMBLFERT.NS", "GNFC.NS", "NAVINFLUOR.NS",
    "PIIND.NS", "SRF.NS", "ATUL.NS", "FINEORG.NS", "TATACHEMICALS.NS", "ALKYLAMINE.NS",
    "EIHOTEL.NS", "TATACONSUM.NS", "JUBLFOOD.NS", "WESTLIFE.NS",
    
    # Consumer & Retail
    "RADICO.NS", "UNITDSPR.NS", "VBL.NS", "CCL.NS", "VMART.NS", "SHOPERSTOP.NS",
    "RELAXO.NS", "ABFRL.NS", "RAYMOND.NS", "EMAMILTD.NS", "JYOTHYLAB.NS", "GILLETTE.NS",
    
    # Media & Entertainment
    "ZEEL.NS", "SUNTV.NS", "NETWORK18.NS", "PVRINOX.NS", "DELTACORP.NS", "NAZARA.NS",
    "EASEMYTRIP.NS", "THOMASCOOK.NS", "WONDERLA.NS",
    
    # New Age Tech & E-commerce
    "NAUKRI.NS", "PAYTM.NS", "POLICYBZR.NS", "LATENTVIEW.NS", "ZOMATO.NS",
    "CRAFTSMAN.NS", "KAYNES.NS", "HBLPOWER.NS",
    
    # Auto Components
    "EXIDEIND.NS", "ARE&M.NS", "BOSCHLTD.NS", "SCHAEFFLER.NS", "ENDURANCE.NS", "SUNDRMFAST.NS",
    "BHARATFORG.NS", "SONACOMS.NS", "SAMVARDHNA.NS", "SUPRAJIT.NS", "GABRIEL.NS",
    
    # Infrastructure & Engineering
    "CONCOR.NS", "LTTS.NS", "KAJARIACER.NS", "CERA.NS", "HINDWARE.NS",
    "GRAPHITE.NS", "AIAENG.NS", "SWANENERGY.NS", "THERMAX.NS", "TRIVENI.NS",
    
    # Power & Energy
    "ADANIENSOL.NS", "NHPC.NS", "SJVN.NS", "SUZLON.NS", "INOXWIND.NS", "GIPCL.NS",
    
    # Renewables & Green Energy
    "AETHER.NS", "CLEAN.NS", "SOLARINDS.NS", "SWSOLAR.NS", "BORORENEW.NS", "HFCL.NS",
    
    # Logistics & Transportation
    "BLUEDART.NS", "VRLLOG.NS", "MAHLOG.NS", "TIINDIA.NS", "GATI.NS",
    "AEGISCHEM.NS", "ALLCARGO.NS", "TCI.NS",
    
    # Textiles & Apparel
    "SIYARAM.NS", "ARVIND.NS", "TRIDENT.NS", "KPRMILL.NS", "SPANDANA.NS",
    
    # Real Estate
    "PRESTIGE.NS", "OBEROIRLTY.NS", "SOBHA.NS", "BRIGADE.NS", "GODREJPROP.NS",
    "PHOENIXLTD.NS", "IBREALEST.NS", "SUNTECK.NS", "MAHLIFE.NS", "LODHA.NS",
    
    # Electrical Equipment
    "CROMPTON.NS", "DIXON.NS", "AMBER.NS", "SYMPHONY.NS", "FINCABLES.NS",
    "FINOLEXIND.NS", "VOLTAMP.NS", "KALYANKJIL.NS", "PGEL.NS",
    
    # Additional High-Momentum Smallcaps
    "RAJESHEXPO.NS", "CGPOWER.NS", "CESC.NS", "KPIGREEN.NS", "CENTURYTEXT.NS", "KKCL.NS", 
    "NAVNETEDUL.NS", "APTECHT.NS", "BSOFT.NS", "RAMCOIND.NS", "KTKBANK.NS", "BALRAMPUR.NS",
    "EIDPARRY.NS", "RENUKA.NS", "BAJAJCON.NS", "SHARDACROP.NS"
]
