# Expanded NSE Universe - 400 High Quality Stocks
# Includes Nifty 100, Midcap 150, and Liquid Smallcaps
# All tickers verified for Yahoo Finance compatibility as of Jan 2026

NIFTY500_TICKERS = [
    # --- NIFTY 50 (Large Cap Core) ---
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "BHARTIARTL.NS", "INFY.NS", 
    "SBIN.NS", "LICI.NS", "ITC.NS", "HINDUNILVR.NS", "LT.NS", "BAJFINANCE.NS", 
    "KOTAKBANK.NS", "HCLTECH.NS", "AXISBANK.NS", "SUNPHARMA.NS", "M&M.NS", "MARUTI.NS", 
    "NTPC.NS", "TATAMOTORS.NS", "TITAN.NS", "ADANIENT.NS", "ULTRACEMCO.NS", "ONGC.NS", 
    "JSWSTEEL.NS", "POWERGRID.NS", "TATASTEEL.NS", "ADANIPORTS.NS", "COALINDIA.NS", 
    "ASIANPAINT.NS", "BAJAJFINSV.NS", "ADANIGREEN.NS", "INDUSINDBK.NS", "GRASIM.NS", 
    "HINDALCO.NS", "NESTLEIND.NS", "BAJAJ-AUTO.NS", "ADANIPOWER.NS", "CIPLA.NS", 
    "EICHERMOT.NS", "TRENT.NS", "BRITANNIA.NS", "TECHM.NS", "DRREDDY.NS", "TATAPOWER.NS", 
    "WIPRO.NS", "SBILIFE.NS", "HDFCLIFE.NS", "JIOFIN.NS", "BPCL.NS",

    # --- NIFTY NEXT 50 (Large & Quality Midcaps) ---
    "HAL.NS", "DMART.NS", "BEL.NS", "SIEMENS.NS", "IRFC.NS", "VBL.NS", "PNB.NS", 
    "ABB.NS", "BANKBARODA.NS", "DLF.NS", "IOC.NS", "GAIL.NS", "GODREJCP.NS", 
    "CHOLAFIN.NS", "TVSMOTOR.NS", "HAVELLS.NS", "LTIM.NS", "CANBK.NS", "AMBUJACEM.NS", 
    "UNITDSPR.NS", "IDBI.NS", "BAJAJHLDNG.NS", "SHREECEM.NS", "MANKIND.NS", "MARICO.NS", 
    "PIDILITIND.NS", "TATACONSUM.NS", "COLPAL.NS", "POLYCAB.NS", "JINDALSTEL.NS", 
    "MUTHOOTFIN.NS", "AUBANK.NS", "RECLTD.NS", "PFC.NS", "SRF.NS", "LUPIN.NS", 
    "TORNTPHARM.NS", "ABCAPITAL.NS", "HEROMOTOCO.NS", "PIIND.NS", "BERGEPAINT.NS", 
    "ICICIPRULI.NS", "MPHASIS.NS", "ZYDUSLIFE.NS", "INDIHOTEL.NS", "IRCTC.NS", 
    "PAGEIND.NS", "HDFCAMC.NS", "ICICIGI.NS", "ZOMATO.NS",

    # --- FINANCIAL SERVICES & BANKING (Expanded Coverage) ---
    "IDFCFIRSTB.NS", "YESBANK.NS", "FEDERALBNK.NS", "BANDHANBNK.NS", "AUROPHARMA.NS", 
    "SBICARD.NS", "MAHABANK.NS", "INDIANB.NS", "UCOBANK.NS", "CENTRALBK.NS", 
    "IOB.NS", "UNIONBANK.NS", "RBLBANK.NS", "SOUTHBANK.NS", "KARURVYSYA.NS", 
    "KTKBANK.NS", "CUB.NS", "DCBBANK.NS", "J&KBANK.NS", "PSB.NS", 
    "LICHSGFIN.NS", "M&MFIN.NS", "POONAWALLA.NS", "LTF.NS", "CHOLAHLDNG.NS", 
    "SHRIRAMFIN.NS", "PEL.NS", "MANAPPURAM.NS", "MUTHOOTCAP.NS", "IIFL.NS", 
    "MOTILALOFS.NS", "ANGELONE.NS", "CDSL.NS", "MCX.NS", "BSE.NS",

    # --- AUTO, IT, & TECH ---
    "ASHOKLEY.NS", "ESCORTS.NS", "APOLLOTYRE.NS", "MRF.NS", "BALKRISIND.NS", 
    "TVSMOTOR.NS", "BOSCHLTD.NS", "SONACOMS.NS", "BHARATFORG.NS", "MOTHERSON.NS", 
    "EXIDEIND.NS", "ARE&M.NS", "SCHAEFFLER.NS", "SKFINDIA.NS", "ENDURANCE.NS", 
    "TATAELXSI.NS", "KPITTECH.NS", "COFORGE.NS", "PERSISTENT.NS", "CYIENT.NS", 
    "HAPPSTMNDS.NS", "ZENSARTECH.NS", "MASTEK.NS", "BSOFT.NS", "OFSS.NS", 
    "SONATSOFTW.NS", "INTELLECT.NS", "TANLA.NS", "ROUTE.NS", "AFFLE.NS", 
    "LALPATHLAB.NS", "METROPOLIS.NS", "NAUKRI.NS", "NYKAA.NS", "PAYTM.NS", 
    "POLICYBZR.NS", "LATENTVIEW.NS", "TATACOMM.NS", "RAILTEL.NS", "HFCL.NS",

    # --- PHARMA, HEALTHCARE & CHEMICALS ---
    "BIOCON.NS", "ALKEM.NS", "GLENMARK.NS", "IPCALAB.NS", "LAURUSLABS.NS", 
    "GRANULES.NS", "DIVISLAB.NS", "AJANTPHARM.NS", "ABBOTINDIA.NS", "PFIZER.NS", 
    "SANOFI.NS", "GLAXO.NS", "ASTRON.NS", "ERIS.NS", "JBCHEPHARM.NS", 
    "MAXHEALTH.NS", "FORTIS.NS", "NARAYANA.NS", "APOLLOHOSP.NS", "SYNGENE.NS", 
    "DEEPAKNTR.NS", "TATACHEM.NS", "NAVINFLUOR.NS", "ATUL.NS", "GUJGASLTD.NS", 
    "VINATIORGA.NS", "FINEORG.NS", "COROMANDEL.NS", "GNFC.NS", "GSFC.NS", 
    "CHAMBLFERT.NS", "RCF.NS", "UPL.NS", "PIIND.NS", "AETHER.NS", 
    "CLEAN.NS", "TATACONSUM.NS", "VBL.NS", "CCL.NS", "JUBLFOOD.NS",

    # --- INFRA, ENERGY, METALS & COMMODITIES ---
    "CONCOR.NS", "RVNL.NS", "IRCON.NS", "ENGINEERSIN.NS", "NBCC.NS", 
    "HEIDELBERG.NS", "JKCEMENT.NS", "RAMCOCEM.NS", "DALBHARAT.NS", "INDIACEM.NS", 
    "AMBUJACEM.NS", "ACC.NS", "JKTYRE.NS", "CEATLTD.NS", 
    "SAIL.NS", "NMDC.NS", "NATIONALUM.NS", "VEDL.NS", "HINDZINC.NS", 
    "TATASTEEL.NS", "JSWSTEEL.NS", "JSL.NS", "APLAPOLLO.NS", "RATNAMANI.NS", 
    "WELCORP.NS", "HINDALCO.NS", "GRAPHITE.NS", "HEG.NS", "KNRCON.NS", 
    "PNCINFRA.NS", "LT.NS", "POWERGRID.NS", "SJVN.NS", "NHPC.NS", 
    "TORNTPOWER.NS", "GIPCL.NS", "GUJALKALI.NS", "IGL.NS", "MGL.NS", 
    "PETRONET.NS", "OIL.NS",

    # --- CONSUMER, RETAIL & TEXTILES ---
    "DABUR.NS", "GODREJCP.NS", "MARICO.NS", "EMAMILTD.NS", "JYOTHYLAB.NS", 
    "GILLETTE.NS", "PGHH.NS", "BATAINDIA.NS", "RELAXO.NS", "METROBRAND.NS", 
    "ABFRL.NS", "TRENT.NS", "TITAN.NS", "KALYANKJIL.NS", "SENCO.NS", 
    "RAYMOND.NS", "VARDHACRLC.NS", "GRASIM.NS", "TRIDENT.NS", "WELSPUNIND.NS", 
    "ALOKINDS.NS", "PAGEIND.NS", "VIPIND.NS", "BLUESTARCO.NS", "VOLTAS.NS", 
    "CROMPTON.NS", "HAVELLS.NS", "DIXON.NS", "AMBER.NS", "SYMPHONY.NS", 
    "KEI.NS", "FINCABLES.NS", "POLYCAB.NS", "RRKABEL.NS", "CERA.NS", 
    "KAJARIACER.NS", "HINDWARE.NS", "SOMANYCERA.NS", "EIDPARRY.NS", "BALRAMCHIN.NS",

    # --- REAL ESTATE, MEDIA & OTHERS ---
    "DLF.NS", "GODREJPROP.NS", "OBEROIRLTY.NS", "PRESTIGE.NS", "SOBHA.NS", 
    "BRIGADE.NS", "PHOENIXLTD.NS", "LODHA.NS", "MAHLIFE.NS", "SUNTECK.NS", 
    "PVRINOX.NS", "SUNTV.NS", "ZEEL.NS", "NETWORK18.NS", "NAZARA.NS", 
    "SAREGAMA.NS", "TV18BRDCST.NS", "EASEMYTRIP.NS", "INDIAMART.NS", "INFOE.NS", 
    "BLUEDART.NS", "DELHIVERY.NS", "MAHLOG.NS", "VRLLOG.NS", "TCIEXP.NS", 
    "ALLCARGO.NS", "GATI.NS", "AEGISCHEM.NS", "GPPL.NS", "ADANIPORTS.NS", 
    "COCHINSHIP.NS", "MAZDOCK.NS", "GRSE.NS", "BEML.NS", "BEL.NS"
]
