# NIFTY 500 constituent tickers (NSE suffixed)
# This is a broader, more representative universe for backtesting
# Includes large caps, midcaps, and liquid smallcaps

NIFTY500_TICKERS = [
    # Large caps (existing)
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", "KOTAKBANK.NS",
    "SBIN.NS", "AXISBANK.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "HCLTECH.NS", "WIPRO.NS",
    "TECHM.NS", "LT.NS", "ASIANPAINT.NS", "HINDUNILVR.NS", "ITC.NS", "TITAN.NS",
    "MARUTI.NS", "M&M.NS", "EICHERMOT.NS", "SUNPHARMA.NS", "CIPLA.NS", "DRREDDY.NS",
    "APOLLOHOSP.NS", "DIVISLAB.NS", "ADANIENT.NS", "ADANIPORTS.NS", "POWERGRID.NS",
    "NTPC.NS", "TATAPOWER.NS", "ONGC.NS", "COALINDIA.NS", "BHARTIARTL.NS", "HINDALCO.NS",
    "JSWSTEEL.NS", "TATASTEEL.NS", "GRASIM.NS", "UPL.NS", "SBILIFE.NS", "HDFCLIFE.NS",
    "ICICIPRULI.NS", "DLF.NS", "PIDILITIND.NS", "TRENT.NS", "DMART.NS", "NYKAA.NS",
    "BANKBARODA.NS", "PNB.NS", "CANBK.NS", "UNIONBANK.NS", "IDFCFIRSTB.NS", "BANDHANBNK.NS",
    "INDUSINDBK.NS", "FEDERALBNK.NS", "AUBANK.NS", "CHOLAFIN.NS", "LTF.NS", "MUTHOOTFIN.NS",
    "ABCAPITAL.NS", "LICI.NS", "BAJAJHLDNG.NS", "GODREJCP.NS", "MARICO.NS", "COLPAL.NS",
    "BRITANNIA.NS", "DABUR.NS", "NESTLEIND.NS", "HAVELLS.NS", "PAGEIND.NS", "VOLTAS.NS",
    "SIEMENS.NS", "ABB.NS", "ASHOKLEY.NS", "ESCORTS.NS", "BOSCHLTD.NS", "CUMMINSIND.NS",
    "MOTHERSON.NS", "BHEL.NS", "IRCTC.NS", "ADANIGREEN.NS", "ADANIPOWER.NS", "TATACHEM.NS",
    "ALKEM.NS", "LUPIN.NS", "TORNTPHARM.NS", "GLENMARK.NS", "MPHASIS.NS", "PERSISTENT.NS",
    "LTIM.NS", "COFORGE.NS", "INDIAMART.NS", "POLYCAB.NS", "KEI.NS", "APLAPOLLO.NS",
    
    # Additional midcaps and liquid smallcaps (sample expansion to ~200-250 total)
    "BERGEPAINT.NS", "SBICARD.NS", "AMBUJACEM.NS", "SHREECEM.NS", "GAIL.NS", "IOC.NS",
    "BPCL.NS", "HEROMOTOCO.NS", "BAJAJ-AUTO.NS", "TVSMOTOR.NS", "BALKRISIND.NS",
    "MRF.NS", "APOLLOTYRE.NS", "CEAT.NS", "BATAINDIA.NS", "RELAXO.NS", "LAURUSLABS.NS",
    "BIOCON.NS", "AUROPHARMA.NS", "DRREDDYS.NS", "CADILAHC.NS", "GRANULES.NS",
    "IPCALAB.NS", "PFIZER.NS", "GLAXO.NS", "SANOFI.NS", "ABBOTINDIA.NS", "ZYDUSLIFE.NS",
    "JKCEMENT.NS", "RAMCOCEM.NS", "DALBHARAT.NS", "JSWENERGY.NS", "SAIL.NS", "NMDC.NS",
    "VEDL.NS", "NATIONALUM.NS", "JINDALSTEL.NS", "RAJESHEXPO.NS", "TANLA.NS", "ROUTE.NS",
    "TATACOMM.NS", "TATAELXSI.NS", "HAPPSTMNDS.NS", "MINDTREE.NS", "L&TFH.NS", "LICHSGFIN.NS",
    "RECLTD.NS", "PFC.NS", "IRFC.NS", "RVNL.NS", "CONCOR.NS", "APOLLOTYRE.NS",
    "DEEPAKNTR.NS", "AARTI.NS", "BALRAMCHIN.NS", "CHAMBLFERT.NS", "GNFC.NS", "NAVINFLUOR.NS",
    "PIIND.NS", "SRF.NS", "ATUL.NS", "FINEORG.NS", "TATACONSUM.NS", "JUBLFOOD.NS",
    "VARUN.NS", "RADICO.NS", "UNITDSPR.NS", "VBL.NS", "CCL.NS", "ZEEL.NS", "SUNTV.NS",
    "NETWORK18.NS", "HATHWAY.NS", "PVR.NS", "INOXLEISUR.NS", "DELTACORP.NS", "NAUKRI.NS",
    "ZOMATO.NS", "PAYTM.NS", "POLICYBZR.NS", "CARTRADETECH.NS", "LATENTVIEW.NS",
    "KPITTECH.NS", "CYIENT.NS", "ECLERX.NS", "INTELLECT.NS", "OFSS.NS", "SONATSOFTW.NS",
    "RAMCOCEM.NS", "JKPAPER.NS", "GRAPHITE.NS", "WESTLIFE.NS", "METROPOLIS.NS", "THYROCARE.NS",
    "LALPATHLAB.NS", "ASTRAZEN.NS", "ALEMBICPH.NS", "TORNTPOWER.NS", "CROMPTON.NS",
    "DIXON.NS", "AMBER.NS", "SYMPHONY.NS", "BLUEDART.NS", "VRLLOG.NS", "MAHLOG.NS",
    "TIINDIA.NS", "FINCABLES.NS", "AETHER.NS", "CLEAN.NS", "SOLARINDS.NS", "WAAREEENER.NS",
    "SUZLON.NS", "CENTRALBK.NS", "IOB.NS", "MAHABANK.NS", "INDIANB.NS", "J&KBANK.NS",
    "SOUTHBANK.NS", "RBLBANK.NS", "YESBANK.NS", "DCB.NS", "EQUITAS.NS", "UJJIVAN.NS",
    "CGPOWER.NS", "CESC.NS", "JSW.NS", "ADANIENSOL.NS", "HUDCO.NS", "NBCC.NS",
    "REPCOHOME.NS", "PRESTIGE.NS", "PHOENIXLTD.NS", "OBEROIRLTY.NS", "SOBHA.NS", "BRIGADE.NS",
]
